basic/controllers/NewsController.php
<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/3/23
 * Time: 16:03
 */
//1.specify namespace at the top (in basic application usually app\controllers);
namespace app\controllers;

//2.specify 'use' path for used class;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

//3.controller class must extend yii\web\Controller class;
//This line is equivalent to
//class NewsController extends yii\web\Controller
class NewsController extends  Controller
{
    //4.actions are handled from controller functions whose name starts with 'action' and
    //the first letter of each word is uppercase;
   public function dataItems()
   {
       $newList = [
           [ 'id' => 1,'title' => 'First World War', 'date' => '1914-07-28'],
           [ 'id' => 2,'title' => 'Second World War', 'date'=> '1939-09-01'],
           [ 'id' => 3,'title' => 'First man on the moon','date'=>'1969-07-20']
       ];

       return $newList;
   }

    //根据yii2 example P60 将其注释
//    public function actionItemsList()
//    {
//        $newsList = $this->dataItems();
//
//        return $this->render('itemlist',['newsList' => $newsList]);
//    }

//    public function actionItemDetail($id)
//    {
//        $newList = $this->dataItems();
//
//        $item = null;
//        foreach($newList as $n)
//        {
//            if ($id == $n['id']) $item = $n;
//        }
//
//        return $this->render('itemDetail',['item' => $item]);
//    }

    public function actionItemDetail()
    {
        $title = yii::$app->request->get('title');

        $data = $this->data();

        $itemFound = null;

        foreach ($data as $d) {
            if($d['title'] == $title) $itemFound = $d;
        }

        return $this->render('itemDetail',['title' => $title , 'itemFound' => $itemFound]);

    }
    //根据yii2 example P52 增加
    public  function actionAdvTest()
    {
        return $this->render('advTest');
    }

    //根据yii2 example P54 增加
    public function actionResponsiveContentTest()
    {
        $responsive = Yii::$app->request->get('responsive',0);

        if($responsive)
        {
            $this->layout = 'responsive';
        }
        else
        {
            $this->layout = 'main';
        }

        return $this->render('responsiveContentTest',['responsive' => $responsive]);
    }

    public function data()
    {
        return[
            [ "id" => 1, "date" => "2015-04-19", "category" => "business", "title" => "Test news
of 2015-04-19" ],
            [ "id" => 2, "date" => "2015-05-20", "category" => "shopping", "title" => "Test news
of 2015-05-20" ],
            [ "id" => 3, "date" => "2015-06-21", "category" => "business", "title" => "Test news
of 2015-06-21" ],
            [ "id" => 4, "date" => "2016-04-19", "category" => "shopping", "title" => "Test news
of 2016-04-19" ],
            [ "id" => 5, "date" => "2017-05-19", "category" => "business", "title" => "Test news
of 2017-05-19" ],
            [ "id" => 6, "date" => "2018-06-19", "category" => "shopping", "title" => "Test news
of 2018-06-19" ]
        ];
    }

    public function actionItemsList()
    {
        // if missing, value will be null
        $year = yii::$app->request->get('year');
        //if missing,value weill be null
        $category = yii::$app->request->get('category');

        $data = $this->data();
        $filteredData = [];

        foreach($data as $d)
        {
            if(($year !=null)&&(date('Y',strtotime($d['date'])) == $year)) $filteredData[] = $d;
            if(($category !=null)&&($d['category'] ==$category)) $filteredData[] =$d;
        }

        return $this->render ('itemList',['year' =>$year,'category' =>$category,'filteredData' => $filteredData]);
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionInternationalIndex()
    {
        //if missing,value will be 'en'
        $lang = yii::$app->request->get('lang','en');

        yii::$app->language = $lang;

        return $this ->render('internationalIndex');
    }
}

basic/views/news/_copyright.php
<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/3/29
 * Time: 13:14
 */
?>
<div>
    This is text about copyright data for news items
</div>

basic/views/news/advTest.php
<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/4/12
 * Time: 10:52
 */
?>
<span>
    This is a test where we display an adv box in layout view
</span>
<?php $this->beginBlock('blockADV'); ?>

    <b>Buy this fantastic book!</b>
<?php $this->endblock(); ?>

basic/views/news/index.php
<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/4/16
 * Time: 15:50
 */
use yii\helpers\Url;
use yii\helpers\Html;

?>

<b>Filter data by year:</b>
<br />
<ul>
    <?php $currentYear = date('Y'); ?>
    <?php for($year =$currentYear; $year>($currentYear-5); $year--) { ?>
    <li><?php echo Html::a('List items by year' .$year, Url::to(['news/items-list', 'year' => $year ]))?></li>
    <?php }?>
</ul>

<br/>
<b>Filter data by category:</b>
<br/>
<ul>
    <?php $category = ['business','shopping']; ?>
    <?php foreach($category as $category) { ?>
    <li><?php echo Html::a ('List items by category ' .$category,
            Url::to(['news/items-list','category' => $category]) )?></li>
    <?php } ?>
</ul>

<br/><br/>

basic/views/news/internationalIndex.php
<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/4/21
 * Time: 14:28
 */
?>

Requested language for this page is:
<br/>
<b><?php echo yii::$app->language ?></b>

basic/views/news/itemDetail.php
<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/3/28
 * Time: 12:07
 */
// $item is from actionItemDetail?>
<?php //echo $this->context->renderPartail('_copyright'); ?>
<!--<h2>News Item Detail</h2>-->
<!--<br/>-->
<!--Title: <b>--><?php //echo $item['title'] ?><!--</b>-->
<!--<br/>-->
<!--Date: <b>--><?php //echo $item['date'] ?><!--</b>-->

Detail item with title <b><?php echo $title ?></b>
<br/><br/>
<?php if($itemFound !=null) { ?>
<table border="1">
    <?php foreach($itemFound as $key=>$value) { ?>
    <tr>
        <th><?php echo $key ?></th>
        <td><?php echo $value ?></td>
    </tr>
    <?php }?>
</table>

<br/>

url for this items is :<?php echo yii\helpers\Url::to(['news/item-detail','title' => $title]); ?>

<?php } else { ?>
    <i>No item found</i>
<?php } ?>

basic/views/news/itemsList.php
<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/3/24
 * Time: 16:22
 */
//$newlist = [
//    [ 'title' => 'First World War', 'date' => '1914-07-28'],
//    ['title' => 'Second World War', 'date' => '1939-09-01'],
//    ['title' => 'First man on the moon', 'date' => '1969-07-20']
//];
//echo $this->context->renderPartial('_copyright');
?>
<?php if($year !=null) { ?>
<b>List for year <?php echo $year ?></b>
<?php } ?>
<?php if ($category !=null) { ?>
<b>List for category <?php echo $category ?></b>
<?php } ?>

<br /><br />
<!--<table >-->
<!--    <tr>-->
<!--        <th>Title</th>-->
<!--        <th>Date</th>-->
<!--    </tr>-->
<!--    --><?php //foreach($newsList as $item) { ?>
<!--    <tr>-->
<!--        <th><a href="--><?php //echo Yii::$app->urlManager->createUrl(['news/item-detail' ,
//                'id' => $item['id']]) ?><!--">--><?php //echo $item['title'] ?><!--</a></th>-->
<!--        <th>--><?php //echo yii::$app->formatter->asDatetime($item['date'], "php:d/m/Y"); ?><!--</th>-->
<!--    </tr>-->
<!--    --><?php //} ?>
<!--</table>-->

<table border="1">
    <tr>
        <th>Date</th>
        <th>Category</th>
        <th>Title</th>
    </tr>
<?php foreach($filteredData as $fd) { ?>
    <tr>
        <td><?php echo $fd['date'] ?></td>
        <td><?php echo $fd['category'] ?></td>
        <td><?php echo $fd['title'] ?></td>
    </tr>
<?php } ?>
</table>

basic/views/news/responsiveContentTest.php
<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/4/12
 * Time: 15:22
 */
if ($responsive) { ?>
    This layout contains responsive content
<?php } else { ?>
    This layout does not contain responsive content
<?php } ?>